version: 0.2

env:
  shell: bash
  parameter-store:
    ECR_URI: "ECR_URI"
    REPOSITORY_NAME: "ECR_REPOSITORY_NAME-REAT_API"
    REGION: "REGION"

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ECR_URI}
      - aws ecr create-repository --repository-name ${REPOSITORY_NAME} --region ${REGION} || true
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t ${REPOSITORY_NAME} ."
      - "docker tag ${REPOSITORY_NAME}:latest ${ECR_URI}/${REPOSITORY_NAME}:latest"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push ${ECR_URI}/${REPOSITORY_NAME}:latest"
      - printf '[{"name":"APIContainer","imageUri":"%s"}]' ${ECR_URI}/${REPOSITORY_NAME}:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
