FROM node:18.16 AS build
WORKDIR /usr/src/app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM node:18.16.0-alpine3.16
WORKDIR /usr/src/app
COPY package.json .
RUN npm install --production
RUN npm install --save sqlite3
COPY --from=build /usr/src/app/dist dist
EXPOSE 4000
CMD ["npm", "run", "dev"]
