version: "3"
services:
  server:
    image: nickelwickelsr/real-estate-analyzer-toolkit-server-dev
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "4000:4000"
